Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -90,14 +90,34 @@ jobs:
     - name: Collect results
       id: collect_results
       run: |
-        BEST_MODEL=$(minikube ssh "ls /data/model_*.joblib | awk -F'[_ .]' '{print \$3, \$0}' | sort -n | head -1 | cut -d' ' -f2")
+        minikube ssh "cat /data/metrics_*.txt" > all_metrics.txt
+        
+        # Check if the metrics file exists and is not empty
+        if [ ! -s all_metrics.txt ]; then
+          echo "No metrics files found!"
+          exit 1
+        fi
+        
+        BEST_MSE=$(sort -n all_metrics.txt | head -n 1)
+        
+        BEST_MODEL=$(minikube ssh "ls /data/model_*.joblib | sort -t '_' -k2,2n | head -1")
 
         if [ -z "$BEST_MODEL" ]; then
           echo "No model file found in /data/"
           exit 1
         fi
+
+        echo "Best MSE: $BEST_MSE"
         echo "Best Model: $BEST_MODEL"
-        
+
+        minikube ssh "cat $BEST_MODEL" > Docker/best_model.joblib
+
+        echo "BEST_MSE=$BEST_MSE" >> $GITHUB_ENV
+        echo "BEST_MODEL_FILE=$BEST_MODEL" >> $GITHUB_ENV
+
+        echo "::set-output name=best_mse::$BEST_MSE"
+        echo "::set-output name=best_model_file::$BEST_MODEL"
+
     # Step 10: Retrieve old model's best MSE score
     - name: Retrieve old model's best MSE score
       id: retrieve_old
@@ -126,7 +146,19 @@ jobs:
         username: mannarn
         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    
+    # Step 3: Copy best model file into Docker folder
+    - name: Copy best model file into Docker folder
+      run: |
+        best_model_file=${{ needs.hyperparameter-tuning.outputs.best_model_file }}
+
+        if [ -z "$best_model_file" ]; then
+          echo "Error: BEST_MODEL_FILE variable is empty."
+          exit 1
+        fi
+
+        echo "Copying best model file: /data/$best_model_file to Docker/best_model.joblib"
+        minikube ssh "cat /data/$best_model_file" > Docker/best_model.joblib
+
     # Step 4: Build and push API Docker image
     - name: Build and push API Docker image
       uses: docker/build-push-action@v2
